---
deployment:
  tasks:
    - export DEPLOYPATH=/home/blendwi1/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp -R .[^.]* $DEPLOYPATH/ 2>/dev/null || true
    - /bin/chmod -R 755 $DEPLOYPATH
    - echo "Deployment completed successfully"

